### ISSUE TITLE
IOError: Unable to open file (Truncated file: eof = 15030288384, sblock->base_addr = 0, stored_eoa = 15807826032)

### ISSUE THREAD

**Issue by songwendong** [JarveeLee/SynthText_Chinese_version#15]
您好，
      我下载了bg_img,seg.h5,depth.h5  然后运行add_more_data.py,就报错了
Traceback (most recent call last):
  File "add_more_data.py", line 73, in <module>
    add_more_data_into_dset(DB_FNAME,more_img_file_path,more_depth_path,more_seg_path)
  File "add_more_data.py", line 39, in add_more_data_into_dset
    depth_db=get_data(more_depth_path)
  File "add_more_data.py", line 31, in get_data
    return h5py.File(DB_FNAME,'r')
  File "/home/zhengjingqing/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/zhengjingqing/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1816)
IOError: Unable to open file (Truncated file: eof = 15030288384, sblock->base_addr = 0, stored_eoa = 15807826032)

**Comment by songwendong** [comment]
请问这是什么问题啊？是hpy5版本问题吗

**Comment by gangliu123** [comment]
Hi, have you solve that problem yet?
