### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by luckydog5** [JarveeLee/SynthText_Chinese_version#49]
Traceback (most recent call last):
  File "gen.py", line 224, in <module>
    main(args.viz)
  File "gen.py", line 131, in main
    RV3 = RendererV3(DATA_PATH,max_time=SECS_PER_IMG)
  File "/Users/zhangshihao/SynthText_Chinese_version/synthgen.py", line 370, in __init__
    self.colorizer = Colorize(data_dir)
  File "/Users/zhangshihao/SynthText_Chinese_version/colorize3_poisson.py", line 145, in __init__
    self.font_color = FontColor(col_file=osp.join(model_dir,'models/colors_new.cp'))
  File "/Users/zhangshihao/SynthText_Chinese_version/colorize3_poisson.py", line 54, in __init__
    self.colorsLAB = np.squeeze(cv.cvtColor(self.colorsLAB[None,:,:],cv.cv.CV_RGB2Lab))
AttributeError: 'module' object has no attribute 'cv'

What should i do if i don't want to  install opencv 2.0? Or i have to install opencv2.0?

**Comment by wsqshiqing** [comment]
You can replace  **CV_RGB2Lab**  with  **CV_RGB2LAB** , in opencv 2.4

**Comment by 1LOVESJohnny** [comment]
Since the update of opencv, I've found this solution. You can replace all the 'cv.cv' into 'cv' only. And correspondingly, change CV_RGB2Lab into COLOR_RGB2Lab. Hope it could help.
