### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by luoyuchen0417** [JarveeLee/SynthText_Chinese_version#58]
Traceback (most recent call last):
  File "gen.py", line 235, in <module>
    main(args.viz)
  File "gen.py", line 136, in main
    RV3 = RendererV3(DATA_PATH, max_time=SECS_PER_IMG)
  File "/home/deepvision/lyc/Syth_ch2/synthgen.py", line 369, in __init__
    self.text_renderer = tu.RenderFont(data_dir)
  File "/home/deepvision/lyc/Syth_ch2/text_utils.py", line 114, in __init__
    self.font_state = FontState(data_dir)
  File "/home/deepvision/lyc/Syth_ch2/text_utils.py", line 437, in __init__
    self.char_freq = cp.load(f)

**Comment by luoyuchen0417** [comment]
how can I fix it ?anybody could tell me
?
